import { useEffect, useState } from "react";
import { FiUsers, FiCheck, FiX, FiPlus, FiShield } from "react-icons/fi";
import DashboardLayout from "../../components/dashboard/DashboardLayout";
import StatCard from "../../components/dashboard/StatCard";
import { createUser, getAllUsers, getPermissions, updateUserAccess, toggleUserStatus, getUserAccess } from "../../services/userService";
import { useAuth } from "../../context/AuthContext";

const ROLES=["ADMIN","OPERATOR","MAINTENANCE","USER"];
const ROLE_STYLES={ADMIN:"bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-400",OPERATOR:"bg-cyan-100 text-cyan-700 dark:bg-cyan-900/40 dark:text-cyan-400",MAINTENANCE:"bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-400",USER:"bg-slate-200 text-slate-600 dark:bg-slate-700 dark:text-slate-300"};

function ManageUsers(){
 const {user:currentUser}=useAuth();
 const [users,setUsers]=useState([]),[permissions,setPermissions]=useState([]),[loading,setLoading]=useState(true),[modal,setModal]=useState(null),[busy,setBusy]=useState(false),[form,setForm]=useState({fullName:"",email:"",password:"",role:"USER",permissions:[]}),[error,setError]=useState("");
 async function load(){try{const [u,p]=await Promise.all([getAllUsers(),getPermissions()]);setUsers(u.data||[]);setPermissions(p.data||[]);}catch(e){setError(e.response?.data?.message||"Failed to load user management data");}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 function openCreate(){setForm({fullName:"",email:"",password:"",role:"USER",permissions:[]});setModal("create");setError("");}
 async function openAccess(u){setBusy(true);setError("");try{const r=await getUserAccess(u.id);setForm({fullName:u.full_name,email:u.email,password:"",role:r.data.user.role,permissions:r.data.permissions});setModal({type:"access",user:u});}catch(e){setError(e.response?.data?.message||"Failed to load privileges");}finally{setBusy(false);}}
 function togglePerm(code){setForm(f=>({...f,permissions:f.permissions.includes(code)?f.permissions.filter(x=>x!==code):[...f.permissions,code]}));}
 function roleDefaults(role){const mapping={ADMIN:permissions.map(p=>p.code),OPERATOR:["dashboard.view","compressors.view","telemetry.view","alerts.view","system.view"],MAINTENANCE:["dashboard.view","compressors.view","telemetry.view","analytics.view","alerts.view","alerts.manage","maintenance.view","maintenance.manage","reports.view","system.view"],USER:["dashboard.view","project.info"]};return mapping[role]||[];}
 function handleRole(role){setForm(f=>({...f,role,permissions:roleDefaults(role)}));}
 async function submit(e){e.preventDefault();setBusy(true);setError("");try{if(modal==="create"){const r=await createUser(form);setUsers(u=>[r.data,...u]);}else{const r=await updateUserAccess(modal.user.id,{role:form.role,permissions:form.permissions});setUsers(u=>u.map(x=>x.id===r.data.id?r.data:x));}setModal(null);}catch(e){setError(e.response?.data?.message||"Unable to save user access");}finally{setBusy(false);}}
 async function toggleStatus(id){setBusy(true);try{const r=await toggleUserStatus(id);setUsers(u=>u.map(x=>x.id===id?{...x,...r.data}:x));}catch(e){alert(e.response?.data?.message||"Failed to update status");}finally{setBusy(false);}}
 const active=users.filter(u=>u.is_active).length;
 const grouped=permissions.reduce((acc,p)=>(acc[p.category]=[...(acc[p.category]||[]),p],acc),{});
 return <DashboardLayout><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-6"><div><span className="text-xs font-bold uppercase tracking-[0.2em] text-purple-500">Administration</span><h2 className="text-3xl font-black text-slate-900 dark:text-white mt-2">User & Access Management</h2><p className="text-sm text-slate-500 dark:text-slate-400 mt-2">Create accounts, assign roles and set exact privileges for each person.</p></div><button onClick={openCreate} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold px-4 py-3"><FiPlus/> Add User</button></div>
 {error&&<div className="mb-5 p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 dark:bg-red-950/30 dark:border-red-900 dark:text-red-300 text-sm">{error}</div>}
 <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-8"><StatCard title="Total Accounts" value={users.length} color="text-cyan-600 dark:text-cyan-400" icon={FiUsers}/><StatCard title="Active" value={active} color="text-emerald-600 dark:text-emerald-400" icon={FiCheck}/><StatCard title="Deactivated" value={users.length-active} color="text-red-600 dark:text-red-400" icon={FiX}/></div>
 <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 dark:bg-slate-900/60"><tr className="text-left text-[11px] text-slate-500 uppercase tracking-wider"><th className="py-3 px-4">User</th><th className="py-3 px-4">Role</th><th className="py-3 px-4">Privileges</th><th className="py-3 px-4">Status</th><th className="py-3 px-4">Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-slate-100 dark:border-slate-700"><td className="py-4 px-4"><p className="font-bold text-slate-900 dark:text-white">{u.full_name}</p><p className="text-xs text-slate-500">{u.email}</p></td><td className="py-4 px-4"><span className={`px-2.5 py-1 rounded-full text-[11px] font-bold ${ROLE_STYLES[u.role]}`}>{u.role}</span></td><td className="py-4 px-4"><span className="text-xs text-slate-600 dark:text-slate-300">{u.permissions?.length||0} permissions</span></td><td className="py-4 px-4"><span className={`px-2.5 py-1 rounded-full text-[11px] font-bold ${u.is_active?"bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400":"bg-slate-200 text-slate-500"}`}>{u.is_active?"Active":"Deactivated"}</span></td><td className="py-4 px-4"><div className="flex flex-wrap gap-2"><button disabled={u.id===currentUser?.id||busy} onClick={()=>openAccess(u)} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-600 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-700 disabled:opacity-50"><FiShield/> Access</button><button disabled={u.id===currentUser?.id||busy} onClick={()=>toggleStatus(u.id)} className="px-3 py-2 rounded-lg border border-slate-300 dark:border-slate-600 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-700 disabled:opacity-50">{u.is_active?"Deactivate":"Activate"}</button></div></td></tr>)}</tbody></table>{loading&&<div className="p-6 text-sm text-slate-400">Loading users…</div>}{!loading&&!users.length&&<div className="p-10 text-center text-slate-400">No users found.</div>}</div></div>
 {modal&&<div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-sm"><div className="w-full max-w-3xl max-h-[90vh] overflow-y-auto bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-700 p-6"><div className="flex items-center justify-between mb-6"><div><h3 className="text-xl font-black text-slate-900 dark:text-white">{modal==="create"?"Create User":"Configure User Access"}</h3><p className="text-sm text-slate-500 mt-1">Choose a role and the exact privileges this account can use.</p></div><button onClick={()=>setModal(null)} className="text-slate-400">✕</button></div><form onSubmit={submit} className="space-y-5">{modal==="create"&&<div className="grid md:grid-cols-2 gap-4"><input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder="Full name" className="rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 px-4 py-3"/><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email" className="rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 px-4 py-3"/><input required type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Temporary password" className="rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 px-4 py-3"/></div>}{modal!=="create"&&<div className="rounded-xl bg-slate-50 dark:bg-slate-800 p-4"><p className="font-bold text-slate-900 dark:text-white">{form.fullName}</p><p className="text-xs text-slate-500">{form.email}</p></div>}<div><label className="text-xs font-bold uppercase text-slate-500">Role</label><select value={form.role} onChange={e=>handleRole(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 px-4 py-3">{ROLES.map(r=><option key={r}>{r}</option>)}</select></div><div className="grid md:grid-cols-2 gap-4">{Object.entries(grouped).map(([cat,items])=><div key={cat} className="rounded-xl border border-slate-200 dark:border-slate-700 p-4"><h4 className="font-bold text-slate-900 dark:text-white mb-3">{cat}</h4>{items.map(p=><label key={p.code} className="flex items-start gap-3 py-2 cursor-pointer"><input type="checkbox" checked={form.permissions.includes(p.code)} onChange={()=>togglePerm(p.code)} className="mt-1 accent-cyan-500"/><span><span className="block text-sm font-semibold text-slate-800 dark:text-slate-200">{p.label}</span><span className="block text-xs text-slate-500 mt-0.5">{p.description}</span></span></label>)}</div>)}</div><button disabled={busy} className="w-full rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold py-3 disabled:opacity-60">{busy?"Saving…":"Save Access"}</button></form></div></div>}
 </DashboardLayout>;
}
export default ManageUsers;
